
#
# Welcome to the MiniRanks configuration file.
# This file contains all the settings for the plugin.
# We try to keep this file as simple as possible.

# please change these before using the plugin
# you can keep the database name as it is in most cases
database-settings:
  host: "localhost"
  port: 3306
  database: "miniranks"
  username: "root"
  password: "password"
  table: "miniranks"
  rank-table: "miniranks_ranks"

rank-settings:
  default-rank: "&8Default"

# The following settings are for the things ive planned for the next update


