name: Miniranks
version: '${project.version}'
main: me.galaxic.miniranks.Miniranks
api-version: 1.16
authors: [ Galaxic ]
description: MiniRanks is a simple rank plugin that is made to be the most simple it can be

commands:
  miniranks:
    description: "Manage ranks"
    aliases:
      - mrank
      - rank
      - ranks
      - mranks
      - minirank
  players:
    description: "Manage players"

permissions:
  miniranks.rank.set:
    description: "Set a player's rank"
  miniranks.rank.create:
    description: "Create a rank"
  miniranks.rank.delete:
      description: "Delete a rank"
  miniranks.rank.perms.manage:
      description: "Manage rank permissions"
  miniranks.players:
    description: "Manage players"
  miniranks.rank.edit:
    description: "Edit a rank"



