name: Miniranks
version: '${project.version}'
main: me.galaxic.miniranks.Miniranks
api-version: 1.18
authors: [ Galaxic ]
description: MiniRanks is a simple rank plugin that is made to be the most simple it can be

commands:
  rank:
    description: "Manage ranks"
  players:
    description: "Manage players"
